version: "2"
services:
    imooc_redis:
        image: daocloud.io/redis
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - /data/www/imooc/logs/redis/:/var/log/redis/
            - /data/www/imooc/work_run/redis/:/var/run/redis/
            - /data/www/imooc/deployment/redis/conf.d/redis.conf:/etc/redis/redis.conf
            - /data/www/imooc/work_run/redis_db:/var/lib/redis
        command: bash -c "redis-server /etc/redis/redis.conf"
        expose:
            - "6379"
        container_name: server_redis
    imooc_service:
        image: cajan2/imooc:1.0
        volumes:
            - /data/www/imooc:/data/www/imooc
            - /data/media/imooc/static:/data/media/imooc/static
            - /data/www/imooc/logs/django/:/var/logs/django/
            - /data/www/imooc/logs/gunicorn/:/var/logs/gunicorn/
            - /data/www/imooc/work_run/celery/:/var/run/celery/
        command: /usr/local/bin/gunicorn -c /etc/gunicorn.conf wsgi:application
        expose:
            - "80"
        links:
            - imooc_redis
        environment:
            - TZ=Asia/Shanghai
            - DB_HOST=$DB_HOST
            - DB_PASSWORD=$DB_PASSWORD
            - CACHE_DEFAULT_HOST=imooc_redis
            - CACHE_CS_HOST=imooc_redis
            - C_FORCE_ROOT=1
            - BROKER_HOST=imooc_redis
        container_name: server_gunicorn

    imooc_nginx:
        image: daocloud.io/nginx
        volumes:
            - /data/www/imooc:/data/www/imooc
            - /data/www/imooc/deployment/docnginx/conf.d:/etc/nginx/conf.d
            - /data/media/imooc/static:/data/media/imooc/static
            - /data/www/imooc/deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/www/imooc/logs/nginx/:/var/logs/nginx
            - /data/www/imooc/work_run/nginx/:/var/run/nginx
        links:
            - imooc_service
        ports:
            - "80:80"
        environment:
            - TZ=Asia/Shanghai
        container_name: server_nginx

    imooc_celery:
        image: cajan2/imooc:1.0
        working_dir: /data/www/imooc/
        command: celery -A project worker -B --logfile=/var/logs/celery/celery.logs
        volumes:
          - /data/www/imooc:/data/www/imooc
          - /data/www/imooc/logs/celery/:/var/logs/celery/
          - /data/www/imooc/logs/django/:/var/logs/django/
        links:
            - imooc_redis
        environment:
            - TZ=Asia/Shanghai
            - DB_HOST=$DB_HOST
            - DB_PASSWORD=$DB_PASSWORD
            - CACHE_DEFAULT_HOST=imooc_redis
            - CACHE_CS_HOST=imooc_redis
            - C_FORCE_ROOT=1
            - BROKER_HOST=imooc_redis
        container_name: server_celery
